config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/', {to: 'welcome#home', as: :root})
  get '/about', {to: 'welcome#about'}
  get '/contacts/new', {to: 'contacts#new'}
  post '/contacts', {to: 'contacts#create' }

  resources :products do
    resources :reviews, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
belongs_to :user

    validates :title, presence: true, uniqueness: true

    validates :price,
            numericality:
              { greater_than: 0 }

    validates :description, presence: true, length: { minimum: 10 }
    has_many :reviews, dependent: :destroy

    before_validation 
    :set_default_price

    before_save
    :capitalize_title

    private

    def set_default_price
        self.price ||= 1
    end

    def capitalize_title
        self.title.capitalize!
    end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :rating, presence:true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    has_secure_password
    has_many :products, dependent: :nullify
    has_many :reviews, dependent: :nullify

    def full_name
        "#{first_name} #{last_name}".strip
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        if session[:user_id].present?
            @current_user || User.find_by(id: session[:user_id])
        end
    end
    helper_method (:current_user)

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def authenticate_user!
        unless user_signed_in?
            flash[:danger] = "You must sign in or sign up first!"
            redirect_to new_session_path
        end
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    # This file was generated with the command:
    # > rails g controller contacts
    def new
      # render :new
    end
  
    def create
      # all parameters from HTTP or the URL come in
       # the hash called `params`
       # params is a `hash with indifferent access`
       # meaning you can access values using string
      # or symbol keys
      # i.e. params[:name] or params['name']
  
      # When we define instance variables in controller
      # actions, we can access them in the corresponding
      # view file
      @name = params[:name]
      @email = params[:email]
      @message = params[:message]
    end
  end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_product, only: [:show, :edit, :update, :destroy]

    def new
        @product = Product.new
    end

    def index
        @products=Product.all
    end

    def edit
    end

    def update
        product_params = params.require(:product).permit(:title, :description, :price)
        if @product.update product_params
            redirect_to product_path(@product)
        else
            render :edit
        end 
    end

    def create
        @product=Product.new product_params
        @product.user = current_user
        if @product.save
            flash[:notice] = "Product created successfully"

            redirect_to product_path(@product)
        else
            render :new
          end
    end

    def show
        @review = Review.new
        @reviews = @product.reviews.order(created_at: :desc)
    end

    def destroy
        @product.destroy
        redirect_to products_path
      end

      private

      def product_params
        params.require(:product).permit(:title, :description, :price)
      end
    
      def find_product
        @product = Product.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    def create
        @product = Product.find(params[:product_id])
        @review = Review.new review_params
        @review.product = @product
        @review.user = current_user

        if @review.save
            redirect_to product_path(@product)
        else
            @reviews = @product.reviews.order(created_at: :desc)
            render 'products/show'
    end
end

    def destroy
        @review = Review.find params[:id]
        @review.destroy
        redirect_to product_path(@review.product)
    end

private

    def review_params
        params.require(:review).permit(:body, :rating)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In"

    else 
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new user_params

        if @user.save 
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end


    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h2>Thank you for contacting us: <%= @name %></h2>

<p>We'll email you back at: <%= @email %></p>

<h4>Your message was:</h4>
<p><%= @message %></p>

app/views/contacts/new.html.erb
<h2>Contact Us</h2>

<%= form_tag contacts_path do %>
  <div>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
    </div>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
    </div>
  <div>
    <%= label_tag :message %>
    <%= text_area_tag :message %>
    </div>
    <%= submit_tag 'Contact Us' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= flash[:notice] || flash[:alert] %> 
  <nav>
    <% if user_signed_in?%>
      Hello <%= current_user.full_name %>,
      <%= link_to "Logout", session_path, method: :delete, 
      data: {confirm: "Are you sure you want to log out?"}%>
    <%else%>
      <%= link_to "Login", new_session_path %> |
      <%= link_to "Sign Up", new_user_path %> 
    <% end %>
    <nav>
      <%= link_to "Home", root_path %>
      |
      <%= link_to "About", about_path %>
      |
      <%= link_to "Contact Us", contacts_new_path %>
      |
      <%= link_to "New Product", new_product_path %>
      |
      <%= link_to "Product Index", products_path %>


    </nav>
    <%= flash[:notice] || flash[:alert] %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
  <%= f.label :price %>
  <%= f.number_field :price %>
</div>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Products</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>All Products</h1>

<% @products.each do |product|  %>
  <div>
    <h2><%= link_to product.title, product_path(product) %></h2>
    <p><%= product.description %></p>
    
    <p>$<%= sprintf('%.2f', product.price) %></p>
    <hr>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Products</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<p><%= @product.description %></p>
<h4>Created by: <%= @product.user.full_name  || 'DELETED'%></h4>


<p>$<%= sprintf('%.2f', @product.price) %></p>

<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure?"} %>

<section>
<h1>Reviews</h1>
<%= form_with(model: [@product, @review], local: true) do |f| %>

    <% if @review.errors.present? %>
    <p class="form-errors">
    <%= @review.errors.full_messages.join(", ") %>
    </p>
    <% end %>

    <div class="form-group">
    <%= f.text_area(
        :body,
        cols: 50,
        rows:5,
        placeholder: "Leave a review!",
        class: "form-control"
    )%>

    <%= f.select(
        :rating, options_for_select([5, 4, 3, 2, 1])
    )%>

    </div>
    <%= f.submit %>

    <% end %>

    <hr>
    <ul class="review-list">
            <% @reviews.each do |review| %>
                <li>
                    <p>
                    <hr>
                    
                    <%= review.rating %>/5 <small>by <%= review.user.full_name  || 'DELETED'%></small>
                    <br> <br>
                    &emsp; <%= review.body %> <br>
                    <small>
                    <%=
                    link_to("Delete", product_review_path(@product, review), method: :delete, data: {
                        confirm: "Are you sure?"
                    })
                    %>
                    </small>
                    <hr>
                    </p>
                </li>
                <% end %>

    </ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |f| %>

    <% if @user.errors.any?%>
        <p>
            <%= @user.errors.full_messages.join(', ')%>
        </p>
    <% end %>

<div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>

app/views/welcome/about.html.erb
<h1>About Us</h1>

app/views/welcome/home.html.erb
<h1>Welcome Home</h1>